### ISSUE TITLE
Recapcha keys don't take

### ISSUE THREAD

**Issue by nikg** [openlab/OGDI-DataLab#15]
Setting RecaptchaPrivateKey & RecaptchaPublicKey values doesn't "take" and causes errors.
Keys set in:

\DataBrowser\DataBrowser.WebRole\Web.Release.config
\DataBrowser\DataBrowser.WebRole\Web.config
\DataBrowser\DataBrowser.Cloud\ServiceConfiguration.Cloud.cscfg
\DataBrowser\DataBrowser.Cloud\ServiceConfiguration.Local.cscfg

End-result the error below:

Source File: e:\sitesroot\0\Views\Shared\Rates.ascx    Line: 72 

Line 70: 
Line 71:    function ShowRecaptcha() {
Line 72:        Recaptcha.create('<%= Ogdi.Azure.Configuration.OgdiConfiguration.GetValue("RecaptchaPupblicKey")%>', "RecaptchaDiv", { callback: Recaptcha.focus_response_field });
Line 73:        document.getElementById('RecaptchaButtons').style.display = "block";
Line 74:    }

**Comment by nikg** [comment]
Found the error -- misspelled key names.

Search for:  
RecaptchaPupblicKey

Replace with: 
RecaptchaPublicKey

**Comment by SyntaxC4** [comment]
I have this fix awaiting a pull request, There are a few issues which need to be resolved before I update the code base.

Thanks for investigating this error, i will update the code shortly

**Comment by SyntaxC4** [comment]
This issue was resolved 8 days ago. Closing down Issue
