### ISSUE TITLE
Query CASE Sensitivity

### ISSUE THREAD

**Issue by nikg** [openlab/OGDI-DataLab#18]
DataService: Fix case sensitivity in field name 

ERROR:
http://datadotgcds2.cloudapp.net/v1/nipoc1/OGSCemeteryIndexNIPOC1/?$filter=TOWNSHIP%20eq%20'Grimsby'
http://datadotgcds2.cloudapp.net/v1/nipoc1/OGSCemeteryIndexNIPOC1/?$filter=township%20eq%20'grimsby'

WORKING:  (both "township" and "Grimsby" must be case sensitive:
http://datadotgcds2.cloudapp.net/v1/nipoc1/OGSCemeteryIndexNIPOC1/?$filter=township%20eq%20'Grimsby'

DataBrowser: Ensure Text Query builder returns results regardless of case sensitivity:

http://datadotgcds2.cloudapp.net/v1/nipoc1/OGSCemeteryIndexNIPOC1/?$filter=TOWNSHIP%20eq%20'Grimsby' 

should work, just as:

http://datadotgc2.cloudapp.net/DataBrowser/nipoc1/OGSCemeteryIndexNIPOC1#param=township%2520eq%2520%2527Grimsby%2527--DataView--Results

**Comment by SyntaxC4** [comment]
As per the Windows Azure Table Storage documentation on [Querying Tables and Entities](http://msdn.microsoft.com/en-us/library/windowsazure/dd894031.aspx) all Filter text in a Query **is** case sensitive.
