### ISSUE TITLE
How can I update existing dataset?

### ISSUE THREAD

**Issue by icsd06ogdi** [openlab/OGDI-DataLab#29]
I want to change one dataset's field types. For the time being my fields are strings and I want to change it to integers.
I tryied from data loader loading the dataset changing the fields' types, saving and seting upload mode to update.

I get the following results:
Metadata for GoatsByRegionBrokenDownByMainCategories was changed.
totalholdings : existing = System.Int32 : new = System.Double
totalgoats : existing = System.Int32 : new = System.Double
goatswhichhavealreadykidded : existing = System.Int32 : new = System.Double
goatsmated : existing = System.Int32 : new = System.Double
othergoatsnotmated : existing = System.Int32 : new = System.Double
otherfemale : existing = System.Int32 : new = System.Double
billygoats : existing = System.Int32 : new = System.Double
othermales : existing = System.Int32 : new = System.Double

What I have to do to update an existing dataset. I just need to change field types. Nothing more.

Thanks in advance.

**Comment by remiolivier** [comment]
The DataLoader allows you to change types in the way you did.

Run the DataLoader then load your file. In the new opened window change types and save. If upload mode set to update doesn't work change it to create.
