### ISSUE TITLE
Change Request - Catalog API

### ISSUE THREAD

**Issue by JMayrbaeurl** [openlab/OGDI-DataLab#32]
It would be quite nice if we could get a ckan style API (http://docs.ckan.org/en/latest/api.html ) for accessing the catalog. Currently I can't find a way to access the metadata of datasets that's shown in the Data Browser portal. Or do I miss something?

Kind regards
Juergen

**Comment by nikg** [comment]
HI Juergen,

The data catalogue (Data Browser) runs on top of a Data Service that provides the necessray API (oData XML/Atom, JSON, etc.) You can see the description & taxonomy here: https://github.com/openlab/DataLab#data-service 

The data + metadata are accessible via the Data Service. 

Let me know any questions!
Nik

**Comment by JMayrbaeurl** [comment]
This seems to be a misunderstanding. I was asking for an API to access the details information of datasets as they are shown in the portal (Data Browser). E.g. the external name of the dataset, the category and the status of a dataset.

**Comment by SyntaxC4** [comment]
As Nik mentioned all of the data from the Data Browser is surfaced thought the Data Service API. You can expose the URLs by running Fiddler (which acts as a proxy to list out request/response information)

I think what you're asking for is documentation on the REST Endpoints (API Docs) is this correct?
