### ISSUE TITLE
Azure 1.7 SDK update

### ISSUE THREAD

**Issue by mcenal** [openlab/OGDI-DataLab#33]
The problem is that the full web auto installer from Microsoft forces upgrading to the newer version of the SDK and that breaks the project.

---

According an instruction document I received from an Andrew Stewart:

"One issue I encountered was with Microsoft.WindowsAzure.StorageClient library reference within DataLoaderGUIApp. I had previously installed Azure SDK for Visual Studio 2012 which had newer libraries. I was required to uninstall these tools and reinstall the SDK for Visual Studio 2010 (November release). I had to rebuild the project and it was fixed, may also have to re-add references manually."

---

I can confirm that this problem does exist in the project.  The DataLoaderGUIApp will not run the XmlSerializer properly when creating a config file with the new SDK.  That was as far as I could get tracing the problem.  

https://github.com/openlab/DataLab/blob/datalab/DataLoader/DataLoader/Helpers/SerializationHelper.cs

line 30 : var serializer = new XmlSerializer(data.GetType()); //This is where it fails in the code.

**Comment by ogdi** [comment]
OK, we'll need to evaluate whether updating everything to VS 2012 makes sense at this point. On the Wiki we specify VS2010 + Azure SDK for it.

**Comment by mcenal** [comment]
Thanks.  However I will note that whether one installs Studio 2010 or
Studio 2012 the web based auto-installer for the SDK automatically picks
1.7 SDK with all updates and the only way to install 1.6 is through the
manual separate install from what I can tell.

On Tue, Sep 4, 2012 at 10:56 AM, OGDI DataLab Team <notifications@github.com

**Comment by remiolivier** [comment]
When updating the project on Visual Studio 2010 with the new Azure 1.7 SDK the Microsoft.WindowsAzure.StorageClient library reference seems to not be updated.

The fix is to remove references to this library and add them again.
Doing this solved any problems I met and DataLoaderGUIApp as well as other solutions works like a charm.
