### ISSUE TITLE
Version of Fluent.dll downgraded when using NuGet

### ISSUE THREAD

**Issue by MiroJ** [openlab/OGDI-DataLab#40]
When following the instructions for wiki installing OGDI DataLab Version 5 on Azure and using NuGet to get the dependencies for DataLaoderGuiApp, the package downgrades the version of the Fluent.dll. It changes the project references away of the Shared folder.

Actually, the NuGet package "OGDI DataLab DataLoaderGuiApp Dependencies" is not required anymore in the current release.

The wiki should not include "OGDI DataLab DataLoaderGuiApp Dependencies" as an item in point 6 under "To install the OGDI DataLab dependencies" heading.

**Comment by MiroJ** [comment]
Wiki was updated.

**Comment by nikg** [comment]
You rock! thanks
