### ISSUE TITLE
FireFox endless loop: p_elSource.attachEvent is not a function

### ISSUE THREAD

**Issue by nikg** [openlab/OGDI-DataLab#6]
Tested with FF 7.0.1 

FireBug returns error: p_elSource.attachEvent is not a function

Page gets "stuck" on loading.

Looks similar to errors caused by FF in BING maps: 
- http://blog.turlov.com/2011/05/fix-for-bing-maps-not-working-in.html  
- http://www.codeproject.com/Articles/190205/Fix-for-Bing-Maps-not-working-in-Firefox-4
- http://stackoverflow.com/questions/5566393/issue-with-bing-map-p-elsource-attachevent-is-not-a-function
- http://code.davidjanes.com/blog/2008/11/08/how-to-dynamically-load-map-apis/

Example: 
http://datadotgc2.cloudapp.net/DataBrowser/Hack%20OpenData/MiltonSplashV1
http://openregina1.cloudapp.net/DataBrowser/openregina/BicyclePaths#param=NOFILTER--DataView--Results

**Comment by SyntaxC4** [comment]
The javascript is implemented in a number of different fashions. 

I've begun the process of moving the javascript around to increase page load performance. Next step is to find all the duplicated JS code and pull it into a javascript file. Simplifying the JS will allow for condensing the javascript into possibly a single file which can be minimized to reduce both the amount of http requests but also the size of the javascript download.
