### ISSUE TITLE
Services project excluded from solution (and not working)

### ISSUE THREAD

**Issue by tonyexpo** [openlab/OGDI-DataLab#8]
Hi

I'm new in github so if I wrote in the wrong place I apologize

I'm trying to use dataservices but I found the cloud project outsite the solution in (DataService\Services)
are you working on it?

Why innerside the servicedefinitions.csdef there are errors like:
"<<<<<<< HEAD:DataService/Services/ServiceConfiguration.Cloud.cscfg".. or "======="... ??????

With the correct cloud project, and working dataservices, will I be able to upload and after download/use a KML file like http://datigis.comune.fi.it/kml/areeverdi.kmz??

many thanks everyone

Antonio

**Comment by tonyexpo** [comment]
sorry, the error file is not the servicedefinition, but the serviceconfigurations (local/cloud)

**Comment by SyntaxC4** [comment]
you may have an old version of the repo. There were some remnants of a merge in the file. These have been removed in the latest version of the code base.

**Comment by tonyexpo** [comment]
thanks
i'll try to download an updated version

**Comment by SyntaxC4** [comment]
Closing this issue as it should be resolved. Please re-open the issue if you run into any more issues.
